name: Build desktop apps

on:
  push:
    tags:
      - 'desktop-v*'

jobs:
  distributable:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_ext: deb
          - os: windows-latest
            artifact_ext: msi
          - os: macos-latest
            artifact_ext: dmg
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}

      - name: Cache KMP tooling
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-v1-${{ hashFiles('*.versions.toml') }}

      - name: Build
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Move
        run: mv ./composeApp/build/compose/binaries/main-release/${{ matrix.artifact_ext }}/*.${{ matrix.artifact_ext }} ./composeApp/build/compose/binaries/main-release/WikWok.${{ matrix.artifact_ext }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./composeApp/build/compose/binaries/main-release/WikWok.${{ matrix.artifact_ext }}
          tag: ${{ github.ref }}
